#!/usr/bin/env python3
"""Build the embedded web UI header (python3 stdlib only).

Reads the SPA sources from webui/, naive-minifies text assets, gzips each one
deterministically, and emits targets/hd-wf2-live/webui_assets.h containing
PROGMEM byte arrays plus a manifest {path, content_type, gzip, length}.

Run from anywhere:
    python3 tools/build_webui.py [--check]

  --check   build in memory and report sizes without writing the header
            (exit 1 if the gzip budget is exceeded)

Budget: total gzipped payload must stay under 120 KB (platform contract).
"""

import argparse
import gzip
import hashlib
import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WEBUI_DIR = os.path.join(ROOT, "webui")
OUT_PATH = os.path.join(ROOT, "targets", "hd-wf2-live", "webui_assets.h")
BUDGET_BYTES = 120 * 1024

# Only these files become embedded assets. mock_server.py / README.md are
# dev-only and never shipped.
INCLUDE_EXT = {
    ".html": "text/html; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".js": "application/javascript; charset=utf-8",
    ".svg": "image/svg+xml",
    ".json": "application/json",
    ".png": "image/png",
    ".ico": "image/x-icon",
}
TEXT_EXT = {".html", ".css", ".js", ".svg", ".json"}
BINARY_EXT = {".png", ".ico"}


def minify_css(text):
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    text = re.sub(r"\s+", " ", text)
    text = re.sub(r"\s*([{}:;,>])\s*", r"\1", text)
    text = text.replace(";}", "}")
    return text.strip()


def minify_js(text):
    """Naive but safe: strip full-line // comments and block comments that
    start a line, drop blank lines, trim indentation. Never touches inline
    comments or anything sharing a line with code (string-literal safety).
    Newlines are preserved so ASI semantics cannot change."""
    out = []
    in_block = False
    for line in text.split("\n"):
        stripped = line.strip()
        if in_block:
            if "*/" in stripped:
                in_block = False
                rest = stripped.split("*/", 1)[1].strip()
                if rest:
                    out.append(rest)
            continue
        if stripped.startswith("//"):
            continue
        if stripped.startswith("/*"):
            if "*/" not in stripped:
                in_block = True
            else:
                rest = stripped.split("*/", 1)[1].strip()
                if rest:
                    out.append(rest)
            continue
        if not stripped:
            continue
        out.append(stripped)
    return "\n".join(out) + "\n"


def minify_html(text):
    text = re.sub(r"<!--.*?-->", "", text, flags=re.S)
    lines = [ln.strip() for ln in text.split("\n")]
    return "\n".join(ln for ln in lines if ln) + "\n"


MINIFIERS = {".css": minify_css, ".js": minify_js, ".html": minify_html}


def gzip_deterministic(data):
    buf = io.BytesIO()
    with gzip.GzipFile(fileobj=buf, mode="wb", compresslevel=9, mtime=0) as gz:
        gz.write(data)
    return buf.getvalue()


def collect_assets():
    assets = []  # (url_path, content_type, raw_len, min_len, gz_bytes)
    for dirpath, dirnames, filenames in os.walk(WEBUI_DIR):
        dirnames[:] = [d for d in dirnames if not d.startswith(("__", "."))]
        for name in sorted(filenames):
            ext = os.path.splitext(name)[1].lower()
            if ext not in INCLUDE_EXT:
                continue
            full = os.path.join(dirpath, name)
            rel = os.path.relpath(full, WEBUI_DIR).replace(os.sep, "/")
            url = "/" + rel
            with open(full, "rb") as fh:
                raw = fh.read()
            if ext in TEXT_EXT and ext in MINIFIERS:
                minified = MINIFIERS[ext](raw.decode("utf-8")).encode("utf-8")
            else:
                minified = raw
            assets.append((url, INCLUDE_EXT[ext], len(raw), len(minified),
                           gzip_deterministic(minified)))
    assets.sort(key=lambda a: a[0])
    return assets


def c_identifier(url):
    return "kAsset_" + re.sub(r"[^A-Za-z0-9]", "_", url.strip("/"))


def emit_header(assets, build_tag):
    lines = []
    w = lines.append
    w("// AUTO-GENERATED by tools/build_webui.py — DO NOT EDIT BY HAND.")
    w("// Rebuild with: python3 tools/build_webui.py")
    w(f"// Build tag (content hash): {build_tag}")
    w("//")
    w("// Serving notes for web_server.cpp:")
    w("//   - every asset is gzip-compressed: send Content-Encoding: gzip")
    w("//   - map request path \"/\" to \"/index.html\"")
    w("//   - unknown non-/api/ paths should fall back to /index.html (SPA)")
    w("//   - use kWebuiBuildTag as the ETag value")
    w("#pragma once")
    w("")
    w("#include <cstddef>")
    w("#include <cstdint>")
    w("")
    w("#if defined(ARDUINO) || defined(ESP_PLATFORM)")
    w("#include <pgmspace.h>")
    w("#else")
    w("#ifndef PROGMEM")
    w("#define PROGMEM")
    w("#endif")
    w("#endif")
    w("")
    w("namespace amg::flightwall::webui {")
    w("")
    for url, ctype, _raw, _minified, gz in assets:
        ident = c_identifier(url)
        w(f"// {url} ({len(gz)} bytes gzipped)")
        w(f"static const std::uint8_t {ident}[] PROGMEM = {{")
        for i in range(0, len(gz), 16):
            chunk = gz[i:i + 16]
            w("    " + " ".join(f"0x{b:02x}," for b in chunk))
        w("};")
        w("")
    w("struct AssetManifestEntry {")
    w("  const char* path;")
    w("  const char* content_type;")
    w("  bool gzip;")
    w("  const std::uint8_t* data;")
    w("  std::size_t length;")
    w("};")
    w("")
    w("static const AssetManifestEntry kWebuiAssets[] PROGMEM = {")
    for url, ctype, _raw, _minified, gz in assets:
        w(f'    {{"{url}", "{ctype}", true, {c_identifier(url)}, {len(gz)}u}},')
    w("};")
    w("")
    w(f"static const std::size_t kWebuiAssetCount = {len(assets)}u;")
    w(f'static const char kWebuiBuildTag[] PROGMEM = "{build_tag}";')
    w("")
    w("}  // namespace amg::flightwall::webui")
    w("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Build embedded web UI header")
    parser.add_argument("--check", action="store_true",
                        help="report sizes only, do not write the header")
    args = parser.parse_args()

    assets = collect_assets()
    if not assets:
        print("error: no assets found under webui/", file=sys.stderr)
        return 1

    digest = hashlib.sha256()
    for url, _ctype, _raw, _minified, gz in assets:
        digest.update(url.encode())
        digest.update(gz)
    build_tag = digest.hexdigest()[:16]

    total_raw = sum(a[2] for a in assets)
    total_min = sum(a[3] for a in assets)
    total_gz = sum(len(a[4]) for a in assets)

    print(f"{'asset':<28} {'raw':>8} {'minified':>9} {'gzip':>8}")
    for url, _ctype, raw, minified, gz in assets:
        print(f"{url:<28} {raw:>8} {minified:>9} {len(gz):>8}")
    print("-" * 56)
    print(f"{'TOTAL':<28} {total_raw:>8} {total_min:>9} {total_gz:>8}")
    print(f"budget: {total_gz} / {BUDGET_BYTES} bytes "
          f"({100.0 * total_gz / BUDGET_BYTES:.1f}% of 120 KB)")
    print(f"build tag: {build_tag}")

    if total_gz >= BUDGET_BYTES:
        print("error: gzip total exceeds the 120 KB contract budget",
              file=sys.stderr)
        return 1

    if args.check:
        print("(--check: header not written)")
        return 0

    header = emit_header(assets, build_tag)
    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(header)
    print(f"wrote {OUT_PATH} ({len(header)} chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
